name: Test Script

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get install -y bats zip

      - name: Run tests
        run: bats tests/tlock-test.bats

      - name: Run file type tests
        run: bats tests/tlock-filetype-tests.bats
